# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-11 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_file',
            field=models.ImageField(default='image.png', upload_to='images/'),
        ),
    ]
