# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-11 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_image_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_file',
        ),
        migrations.AddField(
            model_name='image',
            name='image_path',
            field=models.ImageField(default='image.png', upload_to='gallery/'),
        ),
    ]
